### ISSUE TITLE
Missing tugboat IP for au-syd region

### ISSUE THREAD

**Issue by willholley** [IBM-Cloud/kube-samples#103]
Applying the public network isolation policies to a cluster in au-syd (with logging enabled), shows that it's denying access to `135.90.69.82/32`. This appear to be a valid tugboat IP, so should be allow-listed.

**Comment by Rachael-Graham** [comment]
Thanks, you're correct. PR here https://github.com/IBM-Cloud/kube-samples/pull/104

**Comment by Rachael-Graham** [comment]
merged! closing.
