### ISSUE TITLE
Support query on  CIS Kubernetes benchmark. 

### ISSUE THREAD

**Issue by Prakashckesavan** [IBM-Cloud/kube-samples#270]
Hi,

I was trying to create an argocd app for our project for CIS Kubernetes benchmark. 

We have kubernetes clusters in our project from aks,eks,gks, and iks.
Do [cis-kube-benchmark](https://github.com/IBM-Cloud/kube-samples/tree/master/cis-kube-benchmark)   supports all of them or it is only for the iks clusters. Can we run this in all the 4 clusters

document  referred:  

https://cloud.ibm.com/docs/containers?topic=containers-cis-benchmark#cis-benchmark-use

**Comment by rtheis** [comment]
@Prakashckesavan that is specifically designed for IKS. I don't know how well it will handle other services such as AKS, EKS, or GKE.

**Comment by Prakashckesavan** [comment]
Will is support ibm openshift clusters.

**Comment by rtheis** [comment]
@Prakashckesavan yes, this supports Red Hat OpenShift on IBM Cloud clusters.  See https://cloud.ibm.com/docs/openshift?topic=openshift-cis-benchmark#cis-benchmark-use.

**Comment by Prakashckesavan** [comment]
Hi Thanks for the response , do we have something like this to bring this up to prometheus  metrics- This one installs kube bench and makes it available with prometheus metrics.  https://artifacthub.io/packages/helm/devopstales/kube-bench-metrics

**Comment by rtheis** [comment]
@Prakashckesavan no

**Comment by Prakashckesavan** [comment]
ok, Thanks for the support , I will be closing this issue , Thanks for your support.
